[package]
name = "easy-alias"
version = "1.0.0"
edition = "2021"
authors = ["Lorenzo Costa <http://www.costa86.tech>"]
description = "A CLI alias manager"
license = "AGPL-3.0-or-later"
keywords = ["cli", "alias", "productivity"]

[dependencies]
home = "0.5.3"
